# .github/workflows/deploy.yml
name: Deploy Vue 3 to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # 使用したいNode.jsのバージョン

    - name: Install dependencies
      run: npm install

    - name: Build and Deploy project
      run: npm run deploy:gh-pages  # 新しいビルドコマンドを実行

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
